---
- name: playbook to runn content
  hosts: dev
  tasks:
    - name: create directory
      ansible.builtin.file:
        name: "{{DIRECTORY}}"
        state: directory
    - name: create file
      ansible.builtin.file:
        name: "{{FILE}}"
        state: touch
    - name: copy content
      ansible.builtin.copy:
        content: "{{CONTENT}}"
        dest: "{{DIRECTORY}}/{{FILE}}"



