---
- name: update mast playbook
  hosts: webservers
  tasks:
    - name: create directory
      ansible.builtin.file:
        name: "{{DIRECTORY}}"
        state: directory
    - name: create file
      ansible.builtin.file:
        name: "{{FILE}}"
        state: touch
    - name: update content
      ansible.builtin.copy:
        content: "{{CONTENT}}"
        dest: "{{DIRECTORY}}/{{FILE}}"
