---
- name: Creat master playbook 
  hosts: all 
  tasks:
    - name: Create directory
      ansible.builtin.file:
        name: "{{DIRECTORY}}"
        state: directory
    - name: Crete file
      ansible.builtin.file:
        name: "{{FILE}}"
        state: touch
    - name: copy content
      ansible.builtin.copy:
        content: "{{CONTENT}}"
        dest: "{{DIRECTORY}}/{{FILE}}"

