---
- name: Update the content
  hosts: webservers
  tasks:
    - name: create directory
      ansible.builtin.file:
        name: "{{DIRECTORY}}"
        state: directory
    - name: Create file
      ansible.builtin.file:
        name: "{{FILE}}"
        state: touch
    - name: update content
      ansible.builtin.copy:
        content: "{{CONTENT}}"
        dest: "{{DIRECTORY}}/{{FILE}}"
